# -*- coding: utf-8 -*-
"""737 Python Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c0jj_R0J1n4WJ6U91L2qlc0RuWO6Qqrd
"""

#Anurag Ingle   
#737
#F201315
#0120200328

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('/content/state_wise_crop_production.csv')
print(df.head())



print(df.info())

"""# New Section"""

print(df['Crop'].unique())

print(df['State'].unique())

print(df.columns)

df.groupby(['State', 'Crop'])['Cost of Cultivation (`/Hectare) A2+FL'].sum().sort_values(ascending = True).plot(kind = 'barh',figsize = (13,13))
plt.tight_layout()
plt.title('Crop by State Based on Total Cost of Cultivation (`/Hectare) A2+FL')
plt.legend()
plt.show()

df.groupby(['State', 'Crop'])['Cost of Production (`/Quintal) C2'].sum().sort_values(ascending = True).plot(kind = 'barh',figsize = (13,13))
plt.tight_layout()
plt.title('Crop by State Based on Total Cost of Production (`/Quintal) C2')
plt.legend()
plt.show()

df.groupby(['State', 'Crop'])['Yield (Quintal/ Hectare) '].sum().sort_values(ascending = True).plot(kind = 'barh',figsize = (13,13))
plt.tight_layout()
plt.title('Crop by State Based on Total Yield (Quintal/ Hectare)')
plt.legend()
plt.show()

